name: Compile

on: [push]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: micro-315-project

      - name: Cache build dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: build-dependencies-v3
          path: |
            lib
            gcc-arm-none-eabi-9-2019-q4

      - name: Download e-puck2_main-processor
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: e-puck2/e-puck2_main-processor
          path: lib/e-puck2_main-processor
          submodules: true

      # Not needed for compilation, example for setting up the dev environment
      - name: Download SVD for STM32F407
        if: steps.cache.outputs.cache-hit != 'true'
        run:
          wget -O lib/e-puck2_main-processor/STM32F407.svd
          https://raw.githubusercontent.com/posborne/cmsis-svd/master/data/STMicro/STM32F407.svd

      # Newer toolchains have compatibility issues with Makefile and GDB source maps
      - name: Setup arm-none-eabi-gcc
        if: steps.cache.outputs.cache-hit != 'true'
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: 9-2019-q4
          directory: gcc-arm-none-eabi-9-2019-q4

      # fiam/arm-none-eabi-gcc does not add the bin folder to $PATH
      - name: Add arm-none-eabi-gcc to path
        run:
          echo "${GITHUB_WORKSPACE}/gcc-arm-none-eabi-9-2019-q4/bin" >>
          $GITHUB_PATH

      - name: Compile
        working-directory: micro-315-project/micro-315-project
        run: make

      - name: Upload build artefact
        uses: actions/upload-artifact@v3
        with:
          name: micro-315-project.elf
          path: micro-315-project/micro-315-project/build/micro-315-project.elf
